### ISSUE TITLE
How do you solve issue with baseurl and gadgets not loading

### ISSUE THREAD

**Issue by tallandtree** [cptactionhank/docker-atlassian-jira-software#12]
I found out that when the baseurl is not reachable from the container itself, gadgets are not loaded properly. See also: https://confluence.atlassian.com/jirakb/how-to-fix-gadget-titles-showing-as-__msg_gadget-813697086.html. At least, I _think_ this is the cause of my gadgets in the Jira container not loading properly.

My problem is, I can't get "curl -v baseurl" to work from inside the container. baseurl is equal to the name of the dockerhost, but the dockerhost is not accessible from inside the container.I can ping, but I cannot get it to work with curl.
I keep getting a "Connection refused" from curl, even though I added some rules to open the firewall on the host for the docker0 network. 
Hope you can confirm this with your configuration and have a solution.

**Comment by cptactionhank** [comment]
Sounds to me that you might be having problems about port assignment. Remember from inside the container you should use the default port unless you have applied some changes to server.xml

Kind regards,

Martin Jensen

**Comment by tallandtree** [comment]
Hi,
It is not the port assignment. But I assume something is wrong with the firewall settings on the host. I don't have this issue on another dockerhost. I'll have a better look to the firewall settings and let you know.
Thanks, Mariska.

**Comment by tallandtree** [comment]
I solved it by adding "iptables -I INPUT 4 -i br-88004598752e -j ACCEPT" to my docker host iptables. Where br-88004598752e is the name of my interface to the bridge network I setup for the jira container. Now I need to think about a way to automate this with ansible.
