### ISSUE TITLE
can the /spec/ acceptance test files be used for automated integration?

### ISSUE THREAD

**Issue by jhgorse** [cptactionhank/docker-atlassian-jira-software#15]
Greetings,

Is it possible to use the files in the [/spec/ directory](https://github.com/cptactionhank/docker-atlassian-jira-software/tree/master/spec) to automate the integration of, for example, [JIRA, postgresql](https://github.com/cptactionhank/docker-atlassian-jira-software/blob/1991f725571e018c624ba9a9c44e7e975554776e/spec/acceptance/100_integration_spec.rb#L7), and [nginx+reverse proxy](https://github.com/cptactionhank/docker-atlassian-jira-software/blob/1991f725571e018c624ba9a9c44e7e975554776e/spec/acceptance/100_integration_spec.rb#L65)?

I am somewhat new to Docker and so I am looking for the best ways integrate the elements that it provides in an automated way.

Cheers,
Joe

**Comment by cptactionhank** [comment]
I'm not sure about what you mean exactly.

I have made acceptance tests which does an automated setup process for various configurations which among others include Postgres+NGINX+reverseproxy. 

It's a deliberate choice to keep the image as vanilla or close to the default install as possible with only support a few very commonly used or handy additional features. So to do a whole automated system (I'm guessing upgrading, healtchecking, failover etc.) it all up to you and how you choose to utilize Docker.

**Comment by cptactionhank** [comment]
Yes, the acceptance tests are already used for a CI/CD environment for testing new version of the Docker images.

You should be able to test them yourself using `bundle exec rspec` assuming you have the environment set up, ie. Docker running on localhost and Ruby environment.

**Comment by jhgorse** [comment]
Awesome. Thanks!
