### ISSUE TITLE
Upgrade instructions?

### ISSUE THREAD

**Issue by mikeyp** [cptactionhank/docker-atlassian-jira-software#16]
Looking at the official upgrade docs from Atlasssian leaves me the feeling that upgrades can be complicated, but looking at the Dockerfile, it doesn't seem to be doing an install or anything other than just running Jira. Do you know if there are any extra steps to upgrading from 7.1 to 7.2 or is it pretty straightforward?

**Comment by cptactionhank** [comment]
Upgrading is pretty straight forward and the same exercise as the Atlassian docs says.

Spin up a new container running the newer version of JIRA and making sure that the container contains the same content in the home folder as the previous version does and that it has access to a copy of the same database.

If your lazy as me, you can reuse the home folder and hope there's no additional steps to upgrade; upgrade notes is something that should be available from the JIRA documentation.

My recommendation is to not shutdown your current container and perform a test upgrade using a copy of the home folder and database. If all goes well then switch to use the new container and afterwards remove the old container.
