### ISSUE TITLE
SMTP auth problem

### ISSUE THREAD

**Issue by roasten** [cptactionhank/docker-atlassian-jira-software#19]
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: need username and password for authentication
DEBUG SMTP: protocolConnect returning false, host=xxx, user=daemon, password=<null>
DEBUG SMTP: useEhlo true, useAuth true

Added a real username and password in Jira and passed the Test Connection but still the SMTP handler trying to send with the daemon and null as password, shouldn't this be the username/password we have already configured?

**Comment by cuipengfei** [comment]
same problem here

**Comment by wangtingPapegames** [comment]
I'm in the same boat.
