### ISSUE TITLE
Changing Server ID

### ISSUE THREAD

**Issue by ghost** [cptactionhank/docker-atlassian-jira-software#21]
During my testing and setup of a system using the Jira Software Docker container, I've had the Atlassian Server ID change a couple of times, requiring a new demo license to be created.

I am just wondering if this is a problem in a production environment? Does the Server ID change every time the container is recreated and does this require a new license?

Thanks,
Darren.

**Comment by cptactionhank** [comment]
The Server ID is persisted in the JIRA database, see https://confluence.atlassian.com/jirakb/changing-server-id-for-test-installations-285839562.html. So a new Server ID should only be generated when starting JIRA against an empty database.
