### ISSUE TITLE
Base image OpenJDK not officially supported

### ISSUE THREAD

**Issue by Dominik-K** [cptactionhank/docker-atlassian-jira-software#23]
Hi,

the base image `java:8` is based on OpenJDK. That's why they deprecated this in favor for `openjdk:8`.

Unfortunately, OpenJDK is not officially supported. See [documentation](https://confluence.atlassian.com/adminjiraserver073/supported-platforms-861253018.html) or [JIRA issue](https://jira.atlassian.com/browse/JRA-41589)

**Comment by cptactionhank** [comment]
This is true and due to licensing issue there is not a base image with Oracle's JDK, there is not much to do here than run the unsupported JRE and hope Atlassian will begin support OpenJDK as runtime environment

**Comment by Dominik-K** [comment]
At least, you should use the `openjdk` base image (see https://github.com/cptactionhank/docker-atlassian-jira-software/pull/22) for security updates and best leave a hint in the documentations and Dockerfile. That would be nice.

**Comment by cptactionhank** [comment]
Switching to OpenJDK base image are in the works and you're right there should be a notice in the README

**Comment by rwarren** [comment]
I don't understand the JRE issue for a few reasons:

1. An Alpine image with the Oracle JRE is [readily available](https://hub.docker.com/r/anapsix/alpine-java/) (and extremely popular)
1. Since JIRA 7.6, Atlassian bundles the JRE with the installer anyway!!
    * see the [Atlassian supported platforms page](https://confluence.atlassian.com/adminjiraserver/supported-platforms-938846830.html) where they say "_You don't need to install Java if using the Windows Installer or Linux Installer, as the JRE is bundled with JIRA_"

**Comment by vegai** [comment]
https://community.atlassian.com/t5/Jira-discussions/Java-11-and-OpenJDK-support-for-Atlassian-Server-amp-Data-Center/td-p/872998
