### ISSUE TITLE
Updating the container?

### ISSUE THREAD

**Issue by zyxep** [cptactionhank/docker-atlassian-jira-software#26]
Hey,

Simple question, to update my jira installation to newest version, do I just kill/stop the current container I have and then run the same docker run command but with newer version of your image?

**Comment by cptactionhank** [comment]
The standard Atlassian upgrade procedure applies when using containers as well and you can look it up at the Atlassian documentation site. 

But before you do anything
- Ensure you have a backup of your JIRA home directory
- Ensure you have a backup of your JIRA database

Then you can experiment by eg. starting a new container with a copy of the JIRA home backup

**Comment by zyxep** [comment]
Ah ok, great.
I did redo my setup a little, added volume for jira home dir & install dir since i have to update server.xml to tell it to use SSL :)

And my database is a PostgreSQL in the same network, so it sounds like an easy step to update, thanks.
