### ISSUE TITLE
Unable to set proxy parameters

### ISSUE THREAD

**Issue by ghost** [cptactionhank/docker-atlassian-jira-software#36]
I'm trying to run the latest Jira release (7.7.1) behind a reverse proxy but all the parameters are being ignored. This is the command I used:

```
docker run -d --name="jira" \
    -p 8080:8080 \
    -v ~/data/jira:/var/atlassian/jira \
    -e X_PROXY_NAME=jira.mydomain.com \
    -e X_PROXY_PORT=443 \
    -e X_PROXY_SCHEME=https \
    cptactionhank/atlassian-jira-software:latest
```

I checked inside the container, no sign of proxyName or proxyPort in the server.xml file.
Am I missing something or the server.xml changed a bit?

Thanks,
Francesco

**Comment by cptactionhank** [comment]
Thank you for checking in, this was an error on my part. It has been fixed and should be available shortly, remember to pull the image again from docker hub.
