### ISSUE TITLE
Database connection with environment variables

### ISSUE THREAD

**Issue by vdelacerda** [cptactionhank/docker-atlassian-jira-software#39]
Hi,
for now I configure the database connection width a dbconfig.xml file.
Is there a way to configure it with environment variables ?
Thanks and congrats for your job.

Virgil

**Comment by cptactionhank** [comment]
No, the dbconfig.xml does not exist in image and is created by the installation. Go through the installation setup or make sure that dbconfig.xml exists in advance of starting a container based on this image.

**Comment by vdelacerda** [comment]
OK, thanks
