### ISSUE TITLE
Permission on ${JIRA_HOME}

### ISSUE THREAD

**Issue by petershaw** [cptactionhank/docker-atlassian-jira-software#4]
I always get the error:
JIRA has no permission to either create or write to subdirectory 'caches' of jira.home '/var/atlassian/jira'.

my startupscript is:

```
docker create --restart=no --name "jira" \
  --publish "8001:8080" \
  --volume "/data/jira:/var/atlassian/jira" \
  --link jira-mysql:mysql \
  cptactionhank/atlassian-jira-software:latest
```

/data/jira exists on the docker host.
What am i doing wrong?

**Comment by cptactionhank** [comment]
The default executing user of the JIRA instance is the user `daemon` and thus the home folder mounted external for not needs full permissions for that user.

``` bash
daemon@8186e45735f9:/var/atlassian/jira$ id
uid=1(daemon) gid=1(daemon) groups=1(daemon)
```

You can change the file ownership by running the following on your host machine:

``` bash
sudo chown -R 1:1 /data/jira
```

then JIRA will have permission again to create, update, or delete files in it's home folder.

**Comment by cptactionhank** [comment]
Did you get it to work?

**Comment by paralin** [comment]
I have the same problem. The command you gave me didn't seem to work.

**Comment by cptactionhank** [comment]
Please, can you write the command and the output you ran. To me it sounds very much that you haven't the correct user ownerships on the host machine folders that you guys are trying to mount.

Please check the ownership of your mounted folder in the jira container to be `daemon:daemon` or `1:1` if not there's your problem. Try and validate the ownership and permissions of said folder mounted in the container with `docker exec ...`.

**Comment by tekGuy64** [comment]
I too am having the same problem. I've verified that `daemon:daemon` has ownership of the directories. @cptactionhank is there anyway you could configure your images to allow specification of `PUID` and `PGID` to avoid this issue?

**Comment by paralin** [comment]
I found a fix, basically you have to mount to wherever the VOLUME is specified, and if you mount to an existing location in the container it will have the same permissions (correct perms). So just mount to /var/lib/atlassian I think it was.

**Comment by tekGuy64** [comment]
@paralin sorry, not sure I'm following you. Are you saying the mounted volume location on the host needs to be identical to the directory location in the container?

I.e. `--volume "/var/atlassin/jira:/var/atlassin/jira"`

**Comment by tekGuy64** [comment]
@cptactionhank @paralin figured out the issue on my Docker host. Seems as though, for whatever reason, that the permissions for the directory were not taking affect even when running the command as root. I ended up throwing -f in there to force the permission changes and it magically worked. Thanks for your input.

`sudo chown -Rf 1:1 /somedir`

**Comment by theperm** [comment]
How do you do this when using Docker on windows?

**Comment by LuisUrrutia** [comment]
@tekGuy64 that doesn't works for me (Ubuntu 16.04 and Docker CE installed from docker docs)

**UPDATE**
Solved with:
`docker exec -it --user root CONTAINER_ID bash`
Obviously you have to replace `CONTAINER_ID` with the ID of your running container

And then you run:
`chown -Rf 1:1 /var/atlassin/jira`

Exit from the container and restart your container/service

**Comment by ngocvantran** [comment]
Note for others who have the same issue: `daemon` has id 2 on my container, so you should use @LuisUrrutia's approach above, but replace `1:1` with `daemon:daemon`, meaning:
`chown -Rf daemon:daemon /var/atlassin/jira`

**Comment by rc1** [comment]
Running `chown -Rf 2:2 /var/atlassin/jira` worked for me.

Not sure why I had to do this with a new image. I wasn't upgrading or anything. I was mounting a empty volume

**Comment by edemen** [comment]
I am using docker-compose to run nginx and jwilder/docker-gen for proxy and cptactionhank/atlassian-jira-software behind it.
The following volume configuration works (permission-wise):

```
version: '3.6'
...
services:
    jira:
...
        volumes:
            - jira_home:/var/atlassian/jira
...
volumes:
    jira_home:
        driver_opts:
            type: none
            device: /opt/port/var/atlassian/jira
            o: bind,uid=1(daemon),gid=1(daemon),groups=1(daemon)
```

No need to exec or run anything.
