### ISSUE TITLE
Update from pre-7.7.1 fails, daemon uid changed

### ISSUE THREAD

**Issue by mss** [cptactionhank/docker-atlassian-jira-software#40]
After updating from 7.4 to 7.8, Jira failed to start due to permission problems for the log files.

The "HEADS UP" in the README pointed me to the right direction since I ran into this issue a few times before when switching between Debian and CentOS: On Debian, the user `daemon` has the uid 1 whereas on CentOS and apparently on Alpine it runs as uid 2. Since other people might be less lucky than me, I think it would be good if the HEADS UP was updated. A `chown -R 2:2` on the data volume fixed the issue.

Thanks for your great work BTW!

**Comment by iopsthecloud** [comment]
Just for others replace chmod by chown to make the solution works.

**Comment by BiohZn** [comment]
Thanks for the solution, so the complete working command is `chown -R 2:2 <directory>`

**Comment by cptactionhank** [comment]
yes

**Comment by iamdevnull** [comment]
hello,

why is this issue still open ?!
