### ISSUE TITLE
NullPointerException Error

### ISSUE THREAD

**Issue by XenoPhage** [cptactionhank/docker-atlassian-jira-software#41]
Since moving to 7.8.0 with alpine, we're getting NullPointerException errors when displaying some gadgets on dashboards.  The underlying issue appears to be a missing font package, specifically ttf-dejavu.  You fixed this in docker-atlassian-jira, can we have it fixed here as well?

**Comment by cptactionhank** [comment]
Ported to software and service desk, thanks
