### ISSUE TITLE
Incorrect version of EAP

### ISSUE THREAD

**Issue by matusnovak** [cptactionhank/docker-atlassian-jira-software#48]
The docker image of `cptactionhank/atlassian-jira:eap` contains the **Jira version 8.0.0-m0005** but the same tag on the `cptactionhank/atlassian-jira-software:eap` image contains the old **Jira version 7.1.0-m02** 

I was expecting both `cptactionhank/atlassian-jira:eap` and `cptactionhank/atlassian-jira-software:eap` to have Jira 8.0. 

Would it be possible to fix this?

**Comment by cptactionhank** [comment]
According to Atlassian's JSON feed at `https://my.atlassian.com/download/feeds/eap/jira-software.json` the latest version is:
```javascript
{
  "description": "7.1.0-m02 (TAR.GZ Archive)",
  "zipUrl": "https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.1.0-m02-jira-7.1.0-m02.tar.gz",
  "tarUrl": null,
  "md5": "43c02bd326f9480fe2d700ee7b853cdb",
  "size": "217.2 MB",
  "released": "15-Jan-2016",
  "type": "EAP",
  "platform": "Unix, Mac OS X",
  "version": "7.1.0-m02",
  "releaseNotes": "http://confluence.atlassian.com/display/JIRA/JIRA+7.1.0-m02+Release+Notes",
  "upgradeNotes": "http://confluence.atlassian.com/display/JIRA/JIRA+7.1.0-m02+Upgrade+Notes"
}
```

I can only rely on the officiel Atlassian feeds.

**Comment by matusnovak** [comment]
Ah, that makes sense.
