### ISSUE TITLE
Support for an extra index volume

### ISSUE THREAD

**Issue by kmplngj** [cptactionhank/docker-atlassian-jira-software#53]
I have a server setup with three LVM partitions. 
1) Linux System
2) Jira File Data (Attachments, …) [SAS HDD Space]
3) Jira Database Space [SAS SSD Space]

I like to map the docker volumes to the matching mount point.

Would it be possible to add support for this setup?

**Comment by viceice** [comment]
You can use the mount option of docker to mount any folder to any folder in the container like:

` -v /opt/jira:/var/atlassian/jira -v /opt/jira-data:/var/atlassian/jira/data`
