### ISSUE TITLE
Upgrading Jira software from 7.10.0 to 8.0.2

### ISSUE THREAD

**Issue by YanKawaYu** [cptactionhank/docker-atlassian-jira-software#60]
Hi, thanks for the awesome docker image. I'm using the jira software 7.10.0, and I'm trying to upgrade it to the latest 8.0.2. 
I've tried two ways, manually and with installer. 

When I tried manually, I'm stuck at stop existing Jira instance. I was running the stop-jira.sh and it didn't work. (Error: PID file found but no matching process was found. Stop aborted.) I was using 'ps ef' and trying to kill the process but nothing happened. 

When I tried the installer(atlassian-jira-core-8.0.2-x64.bin), I'm stuck at the error.
Sorry, but I could not find gunzip in path. Aborting.

After I installed the gunzip I got another error.
Error relocating /root/atlassian-jira-core-8.0.2-x64.bin.3339.dir/jre/bin/../lib/amd64/jli/libjli.so: __rawmemchr: symbol not found

So I was wondering is there any instructions on how to upgrade the docker-atlassian-jira-software or could you help me with these problems. 

Thank you very much!

**Comment by hoeghh** [comment]
Never update the container. Use the volume specified to keep the state of the container outside the container. Then stop the container, and start a new one, with the newer version and it will upgrade your database and filesystem. Remember to take a backup before doing this.

**Comment by YanKawaYu** [comment]
Got it. Thanks.
