### ISSUE TITLE
jira-software: Dropdown doesn't populate any items

### ISSUE THREAD

**Issue by neuhausf** [cptactionhank/docker-atlassian-jira-software#7]
If you go to 
https://cptactionhank.github.io/docker-atlassian-jira-software/
the JIRA version dropdown keeps "spinning" and never shows any values.

Another issue is that https://cptactionhank.github.io/docker-atlassian-service-desk is not existing anymore (404).

**Comment by cptactionhank** [comment]
Thank you, i'll look into this as soon as i get some free time.

Kind regards,

Martin Jensen

**Comment by cptactionhank** [comment]
While we're waiting for these changes you can visit https://cptactionhank.github.io/docker-atlassian-jira/ and use this as an example, you just need to update the image name in the commands

**Comment by cptactionhank** [comment]
Should be fixed now
