### ISSUE TITLE
JIRA Startup Failed

### ISSUE THREAD

**Issue by ismarslomic** [cptactionhank/docker-atlassian-jira-software#9]
### My environment:
- OSX 10.11.6
- Docker version 1.12.0-rc4, build e4a0dbc, experimental
### Docker info:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 63
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.788 GiB
Name: moby
ID: 6KZS:ZCKP:VICU:BVCX:UBPK:GYBT:5UPI:G5QY:4LCZ:4RV6:EMJB:R5ON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 36
 System Time: 2016-07-24T20:22:52.599254839Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```
### Steps to reproduce error:
1. `docker pull cptactionhank/atlassian-jira-software`
2. `docker run --detach --publish 8080:8080 cptactionhank/atlassian-jira-software:latest`
3. Go to `http://localhost:8080` and choose first option (Set it up for me)
### Error message:

```
The following plugins are required by JIRA, but have not been started:
Atlassian Navigation Links Plugin (com.atlassian.plugins.atlassian-nav-links-plugin)
Gadget Directory Plugin (com.atlassian.gadgets.directory)
Atlassian JIRA - Plugins - Gadgets Plugin (com.atlassian.jira.gadgets)
Atlassian JIRA - Plugins - Global Issue Navigator (com.atlassian.jira.jira-issue-nav-plugin)
Atlassian JIRA - Plugins - Quick Edit Plugin (com.atlassian.jira.jira-quick-edit-plugin)
Atlassian JIRA - Plugins - REST Plugin (com.atlassian.jira.rest)
Atlassian JIRA - Plugins - Look And Feel Logo Upload Plugin (com.atlassian.jira.lookandfeel)
```

**Comment by ismarslomic** [comment]
This issue was resolved by repeating same steps second time (I removed the Docker container first of course). It seems like "Initializing the plugin system" (configuration step 2) was hanging for some reason the first time.

**Comment by cptactionhank** [comment]
You should consider you instance specifications and also note this is not a problem with neither docker nor the image.

If you only treat the symptom the problem might occur again on the next restart, please see [this](https://confluence.atlassian.com/jirakb/jira-applications-system-plugin-timeout-while-waiting-for-add-ons-to-enable-212173447.html) and [this](https://cptactionhank.github.io/docker-atlassian-jira/) for inspiration on how to fix this.

**Comment by cptactionhank** [comment]
Also thank you for a very nicely formatted issue report 👍

**Comment by ismarslomic** [comment]
Thanks a lot! Really useful!
