### ISSUE TITLE
A Bug in Dockerfile

### ISSUE THREAD

**Issue by KKtheGhost** [cptactionhank/docker-atlassian-jira-software#92]
Martin Aksel Jensen:

The version of binary remains 8.12.0 in the latest Dockerfile, which could cause an unsuccessful upgrade of Jira Software.

**Comment by mickaeltardy** [comment]
While suboptimal, I was able to successfully run the following:

- Take the latest image `docker pull cptactionhank/atlassian-jira-software:latest` with Jira Software 8.14.1 and Jira Core 8.12. That seemed working, but was really confusing;
- Pull the latest codes, modify the Dockerfile, and build myself an image, seems working as well. 
In both cases basic features are working. 

Is there any known pitfalls leading to keep Jira Core 8.12?
